<style scoped>

.hero {
  background-image: url(/uploads/images/cloud-recovery-bg.svg);
  background-size: cover;
  background-position: center;
}

.freedom-bg {
  background-image: url(/uploads/images/freedom-bg.svg);
  background-position: bottom right;
  background-repeat: no-repeat;
  background-size: 25%;
}

.performance-bg {
  background-image: url(/uploads/images/performance-bg.svg);
  background-position: bottom right;
  background-repeat: no-repeat;
  background-size: 60%;
}

.multi-column {
  column-count: 2;
  column-gap: 2.5rem;
}

@media (max-width: 768px) {
	.multi-column {
		column-count: 1;
		column-gap: 0;
	}
}


</style>

<template>
  <Layout>
    <section class="hero flex bg-gray-700 py-12 md:py-24 text-white px-6 xl:px-0">
      <div class="flex flex-col max-w-1200 w-full mx-auto z-10">
        <span class="rfs-text-xl text-yellow1 mb-0">Case Study:</span>
        <h1 class="m-0 p-0 leading-none w-full sm:w-1/2 md:w-5/12">Overstock Achieves Analytic Breakthroughs to Drive Customer Engagement</h1>
        <!-- <a href="/uploads/cs-global-insurance.pdf" target="_blank" class="button yellow mt-8">Download the PDF</a> -->
      </div>
    </section>

    <section class="flex py-12 bg-white px-6 xl:px-0">
      <div class="flex flex-col md:flex-row  justify-evenly max-w-1200 mx-auto">

        <div class="w-full md:w-2/3 p-0 md:pr-10 relative">
          <h3 class="text-gray-500 mb-8">Analytics Innovation at Overstock</h3>
          <div class="text-gray-500 mb-8 md:mb-0">
            <p>Overstock.com is a data and technology driven online retailer located in Salt Lake City, UT. The company has grown to over a billion dollars in revenue by providing high-quality merchandise at attractive prices, backed by exceptional customer service to more than five million unique daily visitors.</p>
            <p>Overstock.com constantly drives business innovation by using new analytic insights generated by their data science team. Due to an oversubscribed enterprise data warehouse, Overstock sought ways to increase data science productivity without adversely impacting the production workloads on the existing data warehouse.</p>
            <p>Intrigued by the Yellowbrick technology, Overstock put the Yellowbrick Data Warehouse through an extensive evaluation. The results showed 10 - 50x performance improvements. Combined with a lower total cost of ownership, Overstock purchased and implemented Yellowbrick.</p>
          </div>

          <h3>Powering Advanced Analytics at Overstock</h3>
          <p>In the first six months of deployment, the Yellowbrick Data Warehouse enabled Overstock data scientists to deliver these previously impossible analytic applications:
</p>
          <h6>Lifetime Value Analysis</h6>
          <ul class="rfs-text-base">
            <li>Overstock.com values long term customer relationships. Using the Yellowbrick Data Warehouse, Overstock data scientists can now perform previously impossible pivot-based time series analysis of Customer Lifetime Value data. This helps identify key influences behind customer acquisition and retention.</li>
            <li>This analysis also revealed optimizations in marketing spend to enable more efficient marketing of key products and increased lifetime value.</li>
          </ul>

          <h6>Sophisticated Historical Campaign Reporting</h6>
          <ul class="rfs-text-base">
            <li>Previously, campaign reporting could only analyze 60 - 90 days of historical data at a time. Wider date spans simply took too long or were too expensive to execute. Using the Yellowbrick Data Warehouse, Overstock now completes multi-year historical campaign reports in minutes, up to 50x faster than before.</li>
            <li>One specific example of previously impossible analytics is analyzing 182 billion rows of historical campaign data in under 2 minutes.</li>
          </ul>

          <h6>Fraud Management</h6>
          <ul class="rfs-text-base">
            <li>The Overstock Fraud Management team analyzes historical order patterns to detect fraudulent activity. Previously, it was impossible to complete a very complex matching of orders with IP addresses on existing platforms, as the heavy computation would either time out or take weeks to complete. With Yellowbrick, this task completed in less than 3 hours.</li>
          </ul>

          <h3>Delivering Real Business Value</h3>
          <p>Overstock is gaining tremendous value from the Yellowbrick Data Warehouse:</p>

          <ul class="rfs-text-base">
            <li>Data scientists are more productive. New insights are often realized in hours or days compared to weeks, and they can ask new questions that previously were not even considered due to constrained analytic capability.</li>
            <li>The fixed budget of an appliance enables data scientists to work without limits, running heavy workloads around the clock without unknowingly increasing spend.</li>
            <li>The data science team now works freely in their own space, relieving pressure on the traditional data warehouse.</li>
          </ul>

          <p>These benefits have been achieved in a demanding production environment where the Yellowbrick Data Warehouse has impressed the Overstock team by its stability as much as by its performance. Yellowbrick Data has also shown a comprehensive and mature approach to the services delivered including:</p>

          <ul class="rfs-text-base">
            <li>One-hour installation compared to multiple days for traditional solutions</li>
            <li>Simple administration, graphical management interface, auto-indexing of all columns</li>
            <li>No grooming, garbage collection, or vacuuming processes to manage</li>
            <li>Easy integration with Overstock enterprise platforms: Tableau, MicroStrategy, Dataiku, Syncsort ETL, and LDAP</li>
          </ul>

          <img src="/uploads/images/resource-library/overstock-diagram.svg" alt="Overstock diagram of data pipeline architecture" class="p-8"/>
          <div class="rfs-text-sm mb-8"><span class="font-semibold">Figure 1:</span> Overstock.com data pipeline architecture</div>


          <h3>Analytics at the Speed of Thought</h3>
          <p>The Yellowbrick Data Warehouse has rapidly become an integral part of the Overstock data warehousing architecture and a key platform to power the Data Science team. As JP Knab, SVP of Marketing and Revenue Creation at Overstock.com said, “Overstock analytics team members can operate at the speed of thought when using the Yellowbrick Data Warehouse. They are now able to quickly find new insights and use those insights to build processes for predictive analysis on a fast- enough timeline to keep up with the quickly-moving world of e-commerce.”</p>

        </div>
				<div class="w-full md:w-1/3">
          <div class="w-full bg-gray-500 shadow-lg p-12 performance-bg text-white">
            <span class="rfs-text-3xl italic">“The Yellowbrick Data Warehouse offers Overstock a solution to the challenge of fast analytics at a reasonable cost. It is a unique combination of simple deployment with fast and scalable analytic execution.”</span>
            <p class="mt-8">- Don Bolling,<br>Manager, Business Intelligence<br>Overstock</p>
          </div>

          <div class="mt-12 w-full bg-white shadow-lg p-10">
            <span class="rfs-text-4xl leading-none">
              <span class="rfs-text-6xl font-bold leading-none">10x-50x</span> Performance Increase
            </span>
          </div>

          <div class="w-full bg-gray-500 shadow-lg p-12 performance-bg text-white">
            <span class="rfs-text-3xl italic">“Not only has the Yellowbrick Data Warehouse proved to be fast and stable in production, their Systems Engineers and Customer Success team has been highly responsive to all our needs”</span>
            <p class="mt-8">- JP Knab,<br>SVP, Marketing/Revenue Creation<br>Overstock</p>
          </div>
        </div>
      </div>
    </section>

    <MoreInfo />

  </Layout>
</template>

<script>
import MoreInfo from '~/components/MoreInfo.vue'

export default {
  metaInfo: {
    title: 'Overstock Case Study',
    meta: [
      { 
        key: 'description',
        name: 'description',
        content: 'Overstock Achieves Analytic Breakthroughs to Drive Customer Engagement with the Yellowbrick Data Warehouse' }
    ]
  },
  components: {
    MoreInfo
  }
}
</script>
